CREATE TABLE IF NOT EXISTS genres(
    id integer generated by default as identity not null primary key,
    name varchar(100) unique
);

CREATE TABLE IF NOT EXISTS mpa(
    id integer generated by default as identity not null primary key,
    name varchar(100) unique
);

CREATE TABLE IF NOT EXISTS films(
    id integer generated by default as identity not null primary key,
    name varchar(200) not null,
    description varchar(200),
    duration int,
    release_date timestamp,
    rating_id integer not null references mpa(id) on delete cascade
);

CREATE TABLE IF NOT EXISTS users(
    id integer generated by default as identity not null primary key,
    login varchar(100) not null,
    name varchar(200),
    email varchar(200) not null,
    birthday timestamp not null
);

CREATE TABLE IF NOT EXISTS friends(
    user_id integer not null references users (id) on delete cascade,
    friend_id integer not null references users (id) on delete cascade,
    primary key (user_id , friend_id)
);

CREATE TABLE IF NOT EXISTS films_like_users(
    film_id integer not null references films (id) on delete cascade,
    user_id integer not null references users (id) on delete cascade,
    primary key (film_id , user_id)
);

CREATE TABLE IF NOT EXISTS films_genres(
    film_id integer not null references films (id) on delete cascade,
    genre_id integer not null references genres (id) on delete cascade,
    primary key (film_id , genre_id)
);